UNIT_MAPPING = {
  "kg" => Mass::Kilogram,
  "kilogram" => Mass::Kilogram,
  "kilograms" => Mass::Kilogram,
  "lb" => Mass::Pound,
  "pound" => Mass::Pound,
  "pounds" => Mass::Pound,
  "m" => Length::Meter,
  "meter" => Length::Meter,
  "meters" => Length::Meter,
  "ft" => Length::Foot,
  "foot" => Length::Foot,
  "feet" => Length::Foot,
  "feets" => Length::Foot,
}.freeze
